### ISSUE TITLE
Does not support JSON files with non-object root elements

### ISSUE THREAD

**Issue by shayneoneill** [hnOsmium0001/godot-json-editor#3]
When opening a JSON file, I jsut get a blank panel and the following error

 res://addons/json_editor/json_dock.gd:75 - Invalid type in function '_gen_object' in base 'PanelContainer (json_dock.gd)'. Cannot convert argument 1 from Array to Dictionary

This is from a standard install off the "Asset library", into Godot v3.2.1

**Comment by shayneoneill** [comment]
Aaaaah I just worked it out. This can only support JSON files whos root is a dictionary, so JSON files which are a list won't work.

**Comment by hnOsmium0001** [comment]
This should be considered a bug. I just went lazy and assumed it's an object root :)

**Comment by shayneoneill** [comment]
Ah yeah, I probably should have tagged that right, my bad :)
